title = "JRM.CC"
theme = "cocoa"

PygmentsCodeFences = true

contentdir = "content"
languageCode = "en-US"
layoutdir = "layouts"

author = "Jeff Minard"

sectionPagesMenu = 'main'

pygmentsuseclasses = true

pluralizelisttitles = false

[markup.goldmark.renderer]
    unsafe= true

[Taxonomies]
    tag = "tags"
    series = "series"
    series-desc = "series-desc"
    section = "section"

[permalinks]
    fixed = "/:title/"
    series = "/series/:title/"
#    blog = "/blog/:slug/"

[params]
    Author = "Jeff Minard"
    CacheBuster = true
    DateForm = "Jan 2, 2006"
    DateFormFull = "Mon Jan 2 2006 15:04:05 MST"
    Description = "Don't panic"
    Email = "you@example.space" # TODO:
    FaviconFile = "img/leaf.ico"
    #GATracker = "XYZ" # TODO:
    GitHub = "//github.com/you" # TODO:
    Initials = "jm" # displayed on single post page; DEPRECATED in v0.3.0
    Lang = "en"
    LinkedIn = "//linkedin.com/in/you" # TODO:
    Twitter = "//twitter.com/you" # TODO:
    #ExtraCssFiles = [ "/css/override.css" ] # relative to public directory
    
